version: "3.8"
services:
  cooky_db:
    image : mongo
    container_name: cooky_db
    ports:
      - 27017:27017
    volumes: 
      -  ./database:/data/db
    command: [
      --auth
    ]
    restart: 
      unless-stopped