version: "3.8"
services:
  cookydb:
    image : mongo
    container_name: cookydb
    ports:
      - 27017:27017
    volumes: 
      -  ./database:/data/db
    command: [
      --auth
    ]
    restart: 
      unless-stopped